## Task 1

##### 1. Write a function to compute 5/0 and use try/except to catch the exceptions 

In [1]:
def compute():
    return 5/0
try:
    compute()
except ZeroDivisionError as e:
    print("its not possible")
except:
    print("any other excepton")
 

its not possible


##### 2. Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"] 

In [2]:
subject=["Americans","Indians"]
verb=["play","watch"]
objects=["Baseball","Cricket"]

list = [(Sub+' '+vrb+' '+Objct+".") for Sub in subject for vrb in verb for Objct in objects]
print("Output:")

for i in list:    
    print(i)

Output:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


## Task 2

##### 1. Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [3]:
def gen_matrix(ipvector, n, increasing=False):
    if not increasing:
        output_matix = np.array([a**(n-1-i) for a in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        output_matix = np.array([a**i for a in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return output_matix

In [6]:
import numpy as np
input_vector = np.array([1,2,3,4,5,6,7])
no_col_output_matix = 6
output_matix_dec_order = gen_matrix(input_vector,no_col_output_matix,False)
output_matix_inc_order = gen_matrix(input_vector,no_col_output_matix,True)

print("The input array is:",input_vector,"\n")
print("Number of columns in output matrix should be:",no_col_output_matix,"\n")
print("Vander matrix of the input array in decreasing order of powers: \n\n",output_matix_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers: \n\n",output_matix_inc_order,"\n")


The input array is: [1 2 3 4 5 6 7] 

Number of columns in output matrix should be: 6 

Vander matrix of the input array in decreasing order of powers: 

 [[    1     1     1     1     1     1]
 [   32    16     8     4     2     1]
 [  243    81    27     9     3     1]
 [ 1024   256    64    16     4     1]
 [ 3125   625   125    25     5     1]
 [ 7776  1296   216    36     6     1]
 [16807  2401   343    49     7     1]] 

Vander matrix of the input array in increasing order of powers: 

 [[    1     1     1     1     1     1]
 [    1     2     4     8    16    32]
 [    1     3     9    27    81   243]
 [    1     4    16    64   256  1024]
 [    1     5    25   125   625  3125]
 [    1     6    36   216  1296  7776]
 [    1     7    49   343  2401 16807]] 

